live_config_reload = true

[env]
TERM = "xterm-256color"

[font]
size = 12

[font.bold]
family = "Monaco"

[font.bold_italic]
family = "Monaco"

[font.italic]
family = "Monaco"

[font.normal]
family = "Monaco"
