(setq gc-cons-threshold (eval-when-compile (* 1024 1024 1024)))
(setq package-enable-at-startup nil)
(setq native-comp-async-report-warnings-errors nil)
(load-file (expand-file-name "exec-path-from-shell.el" user-emacs-directory))
(exec-path-from-shell-initialize)
(when (eq system-type 'darwin)
  (setq native-comp-driver-options '("-Wl,-w")))
